planner/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from tasks.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<day_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^new/$', views.add_day, name='new_day'),
    url(r'^(?P<day_id>[0-9]+)/edit/$', views.edit_day, name='edit_day')
]

tasks/models.py
from django.db import models
from datetime import datetime    


class Day(models.Model):

    title = models.CharField(max_length=100, blank=True)
    created_date = models.DateTimeField(default=datetime.now)
    day = models.DateField(unique=True, default=datetime.now)
    daily_goal = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return self.title

class Task(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    task_text = models.CharField(max_length=600, null=True, blank=True)

    def __str__(self):
        return self.task_text

tasks/forms.py
from django.contrib.admin.widgets import AdminDateWidget

from django import forms

from .models import Day, Task



class DayForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = ('title', 'day', 'daily_goal')
        widgets = {
            'day': forms.DateInput(attrs={'class': 'datepicker'})
            }

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ('day',)
        labels = {
            'task_text': '',
        }

tasks/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader, RequestContext

from .models import Day, Task
from .forms import DayForm, TaskForm


def index(request):
    day_list = Day.objects.all().order_by('day')
    return render(request, 'tasks/index.html', {'day_list':day_list})

def detail(request, day_id):
    day = get_object_or_404(Day, pk = day_id)
    return render(request, 'tasks/detail.html', {'day': day})

def add_day(request):

    if request.method == "POST":
        day = Day.objects.filter(day = request.POST['day'])
        if day.exists():
            return render(request, 'tasks/redir.html', {'day': day[0]})
        else:    
            dform = DayForm(request.POST, instance=Day())
            if dform.is_valid():
                new_day = dform.save()
                for k in request.POST:
                    if not k.endswith('-task_text'):
                        continue
                    cf = TaskForm(request.POST, prefix=k.replace('-task_text', ''), instance=Task())
                    if not cf.is_valid():
                        continue
                    if not cf.cleaned_data['task_text']:
                        continue
                    new_task = cf.save(commit=False)
                    if new_task.id and not new_task.task_text:
                        new_task.delete()
                    else:
                        new_task.day = new_day
                        new_task.save()
                return HttpResponseRedirect('/')
    else:
        dform = DayForm(instance=Day())
        tforms = [TaskForm(prefix=str(x), instance=Task()) for x in range(0,5)]
    return render_to_response('tasks/add_day.html', {'day_form': dform, 'task_forms': tforms}, context_instance=RequestContext(request))

def edit_day(request, day_id):
    day = get_object_or_404(Day, pk = day_id)
    day_form = DayForm(request.POST or None, instance=day)
    tforms = [TaskForm(request.POST or None, prefix=str(i), instance=t) for i, t in enumerate(day.task_set.all().order_by('id'))]
    num_tasks = len(tforms)
    for k in request.POST:
        if not k.endswith('-task_text') or int(k.replace('-task_text', ''))< num_tasks:
            continue
        cf = TaskForm(request.POST, prefix=k.replace('-task_text', ''), instance=Task())
        tforms.append(cf)  
    if day_form.is_valid():
        day_form.save()
        for t in tforms:
            new_task = t.save(commit=False)
            if new_task.id and not new_task.task_text:
                new_task.delete()
            else:    
                new_task.day = day
                new_task.save()
        return HttpResponseRedirect('/')
    return render(request, 'tasks/edit.html', {'day_form': day_form, 'task_forms':tforms})

tasks/templates/tasks/add_day.html
{% extends 'tasks/base.html' %}


{% block content %}

    <h1>New day</h1>

        <form action="/tasks/new/" method="POST" class="post-form">
            {% csrf_token %}
            <div id='day'>{{ day_form.as_p }}</div>
                <ul id="task_list">
                    {% for form in task_forms %}
                        <li>{{ form }}</li>
                    {% endfor %}
                </ul>

                <p><a href="#" id="add_task"><span class="glyphicon glyphicon-plus-sign">
                </span> Add additional task</a></p>

                <button id="safe_button" type="submit" class="save btn btn-default">
                <span class="glyphicon glyphicon-floppy-saved"></span> Save</button>

        </form>

        <a id="back" href="/"><button class="save btn btn-default">
        <span class="glyphicon glyphicon-new-window"></span> Back</button></a>

{% endblock content %}

tasks/templates/tasks/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <img id="logo-main" class="img-responsive center-block"src="{% static "images/logo.jpg" %}" />
        <title>Day planner</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/tasks.css' %}">

        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />

        <script>
        $(function() {
            $( "#id_day" ).datepicker({
                dateFormat: "yy-mm-dd",
                showOn: "button",
                buttonImage: "{% static 'images/calendar.gif' %}",
                buttonImageOnly: true,
                buttonText: "Select date"
            });
            $("#add_task").click(function(){
                var i = $('li').length
                $("#task_list").append('<li><label for="id_'+i+'-task_text"></label><input id="id_'+i+'-task_text" maxlength="600" name="'+i+'-task_text" type="text"></li>')
            })
        });
        </script>
    </head>

    <body>
        <div class="page-header">
            <h1><a href="/">Day planner</a></h1>
        </div>
        <div id = "background" class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
        </br>
    <div id="footer">
        </br>
        <h4>Author: Karolina Blumke</h4>
        <p><a href="mailto:karolina.blumke@gmail.com">karolina.blumke@gmail.com</a></p>
    </div>
    </body>
    </html>

tasks/templates/tasks/detail.html
{% extends 'tasks/base.html' %}


{% block content %}

    <h1>Day Plan for </h1> {{ day.day}}
    <h2>Day title: </h2> {{ day.title }}
    <h3>Daily goal: </h3> {{ day.daily_goal }}
    <h4 id="date">Created: {{ day.created_date }}</h4>
    <h3>List of tasks: </h3>
    <ul>
        {% for task in day.task_set.all %}
                <li>{{ task.task_text }}</li>
        {% endfor %}
    </ul>
    
    <a id="back"href="/">
        <button class="save btn btn-default">
        <span class="glyphicon glyphicon-new-window"></span> Back</button>
    </a>

    <a id="edit" class="btn btn-default" href="/tasks/{{day.id}}/edit">
    <span class="glyphicon glyphicon-edit"></span> Edit</a>

{% endblock content %}

tasks/templates/tasks/edit.html
{% extends 'tasks/base.html' %}


{% block content %}
    <h1>Edit day</h1>

        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ day_form.as_p }}
            <ul id="task_list">
                {% for form in task_forms %}
                    <li>{{ form }}</li>
                {% endfor %}
            </ul>
                <p><a href="#" id="add_task"><span class="glyphicon glyphicon-plus-sign">
                </span> Add additional task</a></p>

                <button id="safe_button" type="submit" class="save btn btn-default">
                <span class="glyphicon glyphicon-floppy-saved"></span> Save</button>

        </form>

            <a id="back" href="/"><button class="save btn btn-default">
            <span class="glyphicon glyphicon-new-window"></span> Back</button></a>

{% endblock content %}

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}


{% block content %}

	{% if day_list %}
	    <h1>Planned days:</h1>
	   	<ul>
		    {% for day in day_list %}
		    	<li><a href="{% url 'detail' day.id %}">{{ day.day }}</a></li>
		    {% endfor %}
	    </ul>
	{% else %}
	    <h4>No days are available.</h4>
	{% endif %}
	
	<a href="{% url 'new_day' %}">
		<button type="submit" class="save btn btn-default">
		<span class="glyphicon glyphicon-plus-sign"></span> Add day</button>
	</a>


{% endblock content %}

tasks/templates/tasks/redir.html
{% extends 'tasks/base.html' %}

{% block content %}
	<h1>Sorry!</h1>
	<p>{{day.day}} is already planned.</p>
	<p>If you want to choose and plan other day - click 'Add day' button.</p>
	<p>If you want to back to index page - click 'Back' button.</p>
	<p>If you want to edit this day - clik 'Edit' button.</p>
	<div class="right">
		<a href="{% url 'new_day' %}">
			<button type="submit" class="save btn btn-default">
			<span class="glyphicon glyphicon-plus-sign"></span> Add day</button>
		</a>
	</div>
	<div class="left">
	    <a href="/">
		    <button class="save btn btn-default">
		    <span class="glyphicon glyphicon-new-window"></span> Back</button>
	    </a>
    </div>
    <div class="center">
	    <a class="btn btn-default" href="/tasks/{{day.id}}/edit">
	    <span class="glyphicon glyphicon-edit"></span> Edit</a>
    </div>
{% endblock content %}